# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 473920c54dc5c3157dcdfe058fd15c6129d8d0861211ac409f5b59df33559b45a86364baeb6e031a00119bbcc3f0d98ce33d7c8ea19df7e02330b3bb8da15a35

test:
  secret_key_base: ba446f5742a82c72296dff3956f6e94d20a98cbe144a410df48efc39aede94e56216a15ada65da4853b455b318e7835ba707a67e67d4be24f22b915cc5dd8e86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
